site_name: GIC DE Assessment - Transactions

nav:0
  - Home: index.md
  - User Guide: user_guide.md
  - Assignment: bank_account_interest.md
  - Guidelines: guidelines.md
  - Issues: issues.md
  - Developer: developer.md
  - CICD: cicd.md

theme:
  name: material

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format