site_name: GIC DE Assessment - Transactions

nav:
  - Home: index.md
  - Assignment: bank_account_interest.md
  - Guidelines: guidelines.md
  - CICD: cicd.md

theme:
  name: material

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format